package automacaoresidencial;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thiago
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    private ArrayList<Dispositivo> lista = new ArrayList();
    
    public TelaPrincipal() {
        initComponents();       
        //Centralizar janela - stackoverflow
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
    //Setter's
    public void setLabelResidencia(String _label) {
        labelResidencia.setText(_label);
    }   
    
    public void setTabelaDispositivos(ArrayList<Dispositivo> _lista) {
        this.lista = _lista;
        //Classe para colorir as linhas da tabela, @author Alessandra stackoverflow
        tabelaDispositivos.setDefaultRenderer(Object.class, new ColorirTabela());            
        attTabela();
        //Coluna invisivel para a classe ColorirTabela funcione
        tabelaDispositivos.getColumnModel().getColumn(1).setMinWidth(0);
        tabelaDispositivos.getColumnModel().getColumn(1).setMaxWidth(0);
        tabelaDispositivos.getColumnModel().getColumn(1).setWidth(0);
    }
    
    //Metodo atualizar a Tabela de forma dinamica
    private void attTabela() {  
        limpaTabela();
        DefaultTableModel dtm = (DefaultTableModel) tabelaDispositivos.getModel();
        int i = 0;
        while(dtm.getRowCount() < lista.size()) {            
            dtm.addRow(new Object[]{ lista.get(i), lista.get(i).getEstado() });
            i++;                                 
        }        
    }
    //Metodo limpar Tabela, linha por linha
    private void limpaTabela() {
        DefaultTableModel dtm = (DefaultTableModel) tabelaDispositivos.getModel();
        while(dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelResidencia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDispositivos = new javax.swing.JTable();
        labelComodo = new javax.swing.JLabel();
        botaoLigaDesliga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Residencia:");

        labelResidencia.setText("MudarEstaLabelComOnomeDaResidencia");

        tabelaDispositivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dispositivos", "<HIDE>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDispositivos);

        labelComodo.setText("Sala:");

        botaoLigaDesliga.setText("Ligar/Desligar");
        botaoLigaDesliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLigaDesligaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelResidencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(botaoLigaDesliga))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelComodo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelResidencia))
                .addGap(18, 18, 18)
                .addComponent(labelComodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLigaDesliga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLigaDesligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLigaDesligaActionPerformed
        try {            
            if(lista.get(tabelaDispositivos.getSelectedRow()).getEstado().equals("Desligado")) {                
                lista.get(tabelaDispositivos.getSelectedRow()).ligar();
                attTabela();
            } else { 
                lista.get(tabelaDispositivos.getSelectedRow()).desligar();
                attTabela();
            }            
        } catch (IndexOutOfBoundsException i){
            System.out.println(i);
        } catch(Exception e) {
            System.out.println(e);
        }       
    }//GEN-LAST:event_botaoLigaDesligaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLigaDesliga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelComodo;
    private javax.swing.JLabel labelResidencia;
    private javax.swing.JTable tabelaDispositivos;
    // End of variables declaration//GEN-END:variables
}
